REASSIGN OWNED BY cocoadm TO postgres;
DROP OWNED BY cocoadm;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM cocoadm;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM cocoadm;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM cocoadm;
DROP DATABASE cocotuto;
DROP SCHEMA cocoapp cascade;
DROP USER cocoadm;
